name = "AdaptiveSG"
uuid = "304fd37e-c786-4c07-85f2-bf782a9834c5"
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.9"

[authors]
name = "Clpr"
email = "zhao1tian1hao1@outlook.com"
